name: Test

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - develop

jobs:
    build:
        runs-on: [self-hosted, Linux]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: "18"

            - name: Install dependencies
              run: |
                  npm i

            - name: Compile
              run: |
                  npx hardhat compile

            - name: Test
              run: |
                  npx hardhat test --parallel
